name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-restore --no-build
    - name: Publish to NuGet
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push **/*.symbols.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet packages
        path: '**/*.nupkg'
        overwrite: true
